{% set version = "0.5.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-lsr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lsr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lsr/lsr_{{ version }}.tar.gz
  sha256: a9ff0b51cdda26b46980a6090d552b24c5e6259b9001629066fd4c7214b5ab02

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('lsr')"           # [not win]
    - "\"%R%\" -e \"library('lsr')\""  # [win]

about:
  home: http://health.adelaide.edu.au/psychology/ccs/teaching/lsr/
  license: MIT
  summary: 'A collection of tools intended to make introductory statistics easier to teach, including wrappers for common hypothesis tests and basic data manipulation. It accompanies Navarro, D. J. (2015). Learning Statistics with R: A Tutorial for Psychology Students and Other Beginners, Version 0.5. [Lecture notes] School
    of Psychology, University of Adelaide, Adelaide, Australia. ISBN: 978-1-326-18972-3. URL: http://health.adelaide.edu.au/psychology/ccs/teaching/lsr/.'
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT

extra:
  recipe-maintainers:
    - conda-forge/r
