{% set version = "0.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lsr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lsr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lsr/lsr_{{ version }}.tar.gz
  sha256: f6d341fbe14875a3dc8950c4759bedbab0903a112c585ea94a2773a48fe7a3ef

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    # we are not sure, why this package is removing the $R env
    - export R=$PREFIX/bin/R           # [not win]
    - set R=%PREFIX%\Scripts\R.exe     # [win]
    - $R -e "library('lsr')"           # [not win]
    - "\"%R%\" -e \"library('lsr')\""  # [win]

about:
  home: http://health.adelaide.edu.au/psychology/ccs/teaching/lsr/
  license: GPL-3
  summary: 'A collection of tools intended to make introductory statistics easier to teach, including wrappers for common hypothesis tests and basic data manipulation. It accompanies Navarro, D. J. (2015). Learning Statistics with R: A Tutorial for Psychology Students and Other Beginners, Version 0.5. [Lecture notes] School
    of Psychology, University of Adelaide, Adelaide, Australia. ISBN: 978-1-326-18972-3. URL: http://health.adelaide.edu.au/psychology/ccs/teaching/lsr/.'
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - dpryan79
